// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwxillg3jKdHvzF2PGWMJT1ywaTb3tP0',
    appId: '1:917484169316:web:77715528d46f261a429771',
    messagingSenderId: '917484169316',
    projectId: 'chatgpt-bot-d0a84',
    authDomain: 'chatgpt-bot-d0a84.firebaseapp.com',
    databaseURL: 'https://chatgpt-bot-d0a84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatgpt-bot-d0a84.appspot.com',
    measurementId: 'G-RP5BWZG741',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS2nwjte4wOBgyMYMsNO9Tt_684TYmItg',
    appId: '1:917484169316:android:a22cd593622a00ce429771',
    messagingSenderId: '917484169316',
    projectId: 'chatgpt-bot-d0a84',
    databaseURL: 'https://chatgpt-bot-d0a84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatgpt-bot-d0a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPO2u-3SSu2sEUPr0M3L1jIGmT4hxRZg',
    appId: '1:917484169316:ios:29bb89b1ce2bd57c429771',
    messagingSenderId: '917484169316',
    projectId: 'chatgpt-bot-d0a84',
    databaseURL: 'https://chatgpt-bot-d0a84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatgpt-bot-d0a84.appspot.com',
    iosBundleId: 'com.example.kouluharjoittelu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPO2u-3SSu2sEUPr0M3L1jIGmT4hxRZg',
    appId: '1:917484169316:ios:18cb5c548c7cfb58429771',
    messagingSenderId: '917484169316',
    projectId: 'chatgpt-bot-d0a84',
    databaseURL: 'https://chatgpt-bot-d0a84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatgpt-bot-d0a84.appspot.com',
    iosBundleId: 'com.example.kouluharjoittelu.RunnerTests',
  );
}
